### PR TITLE
upgrade to rust 1.46.0

### PR DESCRIPTION
**Pull request by mbergkvist**

### CODE REVIEW

**Comment by mbergkvist** [comment]
closes #78

**Comment by seanpianka** [comment]
Can you also add for 1.47.0?

**Comment by mbergkvist** [comment]
Obsoleted by #80

**Comment by mbergkvist** [comment]
> Can you also add for 1.47.0?

PR for 1.47.0 in #80 

If you are interested in a basic rust lambda build image, have a look at https://github.com/nmoutschen/rust-lambda-build-images.

**Pull request closed without merging**
